### ISSUE TITLE
Akeeba Backup Core mouse hover doesn't release

### ISSUE THREAD

**Issue by newburns** [akeeba/awf#6]
When hovering over any tooltips in Joomla Akeeba Backup Core, the tooltips do not disappear. 
This causes them to cover other important fields

**Comment by nikosdion** [comment]
Ah, I see you need personalised consultancy over a GitHub ticket on an unrelated repository I contribute to. Cool. Please send me my personalised consultancy fee of 200 Euros (100 Euros per hour, minimum charge 2 hours, paid in advance) via PayPal to sales at akeeba backup dot com and I'll reply to you.

**Comment by newburns** [comment]
Ahh. I see I posted to the wrong thing. APOLOGIES
:)
I thought this was for Akeeba. Was trying to let the developers know, there is problem with the CSS on the mouseover.

**Comment by nikosdion** [comment]
Two points you should keep in mind:

1. The README of this repository reads "AWF - Akeeba Web Framework. A web application framework for single source standalone web applications, Joomla! components and WordPress plugins. PHP 5.3+, namespaces, MVC, ORM, small footprint." Nowhere does it say Akeeba Backup.

2. The tooltip is supposed to stay on screen until you hover your mouse inside it and then outside it, per the documentation. If you're wondering why, have you ever tried copying text from a tooltip? Exactly.
